<?php

  namespace Database\Seeders;

  use App\Models\Country;
  use Carbon\Carbon;
  use Illuminate\Database\Console\Seeds\WithoutModelEvents;
  use Illuminate\Database\Seeder;

  class CountriesTableSeeder extends Seeder
  {
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
      Country::insert([
        [
          'id' => 1,
          'name' => 'afganistan',
          'flag' => 'afganistan.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 2,
          'name' => 'alemania',
          'flag' => 'alemania.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 3,
          'name' => 'andorra',
          'flag' => 'andorra.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 4,
          'name' => 'angola',
          'flag' => 'angola.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 5,
          'name' => 'antigua y barbuda',
          'flag' => 'antiguaybarbuda.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 6,
          'name' => 'arabia saudita',
          'flag' => 'arabia-saudita.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 7,
          'name' => 'argelia',
          'flag' => 'argelia.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 8,
          'name' => 'argentina',
          'flag' => 'argentina.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 9,
          'name' => 'armenia',
          'flag' => 'armenia.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 10,
          'name' => 'australia',
          'flag' => 'australia.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 11,
          'name' => 'austria',
          'flag' => 'austria.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 12,
          'name' => 'bahamas',
          'flag' => 'bahamas.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 13,
          'name' => 'barein',
          'flag' => 'barein.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 14,
          'name' => 'banglades',
          'flag' => 'banglades.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 15,
          'name' => 'barbados',
          'flag' => 'barbados.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 16,
          'name' => 'belgica',
          'flag' => 'belgica.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 17,
          'name' => 'bielorrusia',
          'flag' => 'bielorrusia.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 18,
          'name' => 'bolivia',
          'flag' => 'bolivia.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 19,
          'name' => 'bosnia y herzegovina',
          'flag' => 'bosnia-y-herzegovina.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 20,
          'name' => 'brasil',
          'flag' => 'brasil.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 21,
          'name' => 'bulgaria',
          'flag' => 'bulgaria.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 22,
          'name' => 'camerun',
          'flag' => 'camerun.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 23,
          'name' => 'canada',
          'flag' => 'canada.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 24,
          'name' => 'catar',
          'flag' => 'catar.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 25,
          'name' => 'republica checa',
          'flag' => 'republica-checa.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 26,
          'name' => 'chile',
          'flag' => 'chile.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 27,
          'name' => 'china',
          'flag' => 'china.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 28,
          'name' => 'ciudad del vaticano',
          'flag' => 'ciudad-del-vaticano.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 29,
          'name' => 'colombia',
          'flag' => 'colombia.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 30,
          'name' => 'congo',
          'flag' => 'congo.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 31,
          'name' => 'corea del norte',
          'flag' => 'corea-del-norte.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 32,
          'name' => 'corea del sur',
          'flag' => 'corea-del-sur.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 33,
          'name' => 'costa de marfil',
          'flag' => 'costa-de-marfil.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 34,
          'name' => 'costa rica',
          'flag' => 'costa-rica.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 35,
          'name' => 'croacia',
          'flag' => 'croacia.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 36,
          'name' => 'cuba',
          'flag' => 'cuba.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 37,
          'name' => 'dinamarca',
          'flag' => 'dinamarca.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 38,
          'name' => 'ecuador',
          'flag' => 'ecuador.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 39,
          'name' => 'egipto',
          'flag' => 'egipto.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 40,
          'name' => 'el salvador',
          'flag' => 'el-salvador.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 41,
          'name' => 'emiratos arabes',
          'flag' => 'emiratos-arabes.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 42,
          'name' => 'escocia',
          'flag' => 'escocia.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 43,
          'name' => 'eslovenia',
          'flag' => 'eslovenia.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 44,
          'name' => 'españa',
          'flag' => 'espania.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 45,
          'name' => 'estados unidos',
          'flag' => 'estados-unidos.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 47,
          'name' => 'finlandia',
          'flag' => 'finlandia.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 48,
          'name' => 'francia',
          'flag' => 'francia.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 49,
          'name' => 'gales',
          'flag' => 'gales.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 50,
          'name' => 'ghana',
          'flag' => 'ghana.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 51,
          'name' => 'grecia',
          'flag' => 'grecia.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 52,
          'name' => 'guatemala',
          'flag' => 'guatemala.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 53,
          'name' => 'guinea',
          'flag' => 'guinea.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 54,
          'name' => 'guyana',
          'flag' => 'guyana.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 55,
          'name' => 'haiti',
          'flag' => 'haiti.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 56,
          'name' => 'honduras',
          'flag' => 'honduras.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 57,
          'name' => 'hong kong',
          'flag' => 'hong-kong.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 58,
          'name' => 'hungria',
          'flag' => 'hungria.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 59,
          'name' => 'india',
          'flag' => 'india.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 60,
          'name' => 'indonesia',
          'flag' => 'indonesia.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 61,
          'name' => 'inglaterra',
          'flag' => 'inglaterra.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 62,
          'name' => 'irak',
          'flag' => 'irak.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 63,
          'name' => 'iran',
          'flag' => 'iran.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 64,
          'name' => 'irlanda',
          'flag' => 'irlanda.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 65,
          'name' => 'israel',
          'flag' => 'israel.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 66,
          'name' => 'italia',
          'flag' => 'italia.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 67,
          'name' => 'jamaica',
          'flag' => 'jamaica.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 68,
          'name' => 'japon',
          'flag' => 'japon.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 69,
          'name' => 'marruecos',
          'flag' => 'marruecos.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 70,
          'name' => 'mexico',
          'flag' => 'mexico.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 71,
          'name' => 'nicaragua',
          'flag' => 'nicaragua.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 72,
          'name' => 'nigeria',
          'flag' => 'nigeria.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 73,
          'name' => 'noruega',
          'flag' => 'noruega.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 74,
          'name' => 'nueva zelanda',
          'flag' => 'nueva-zelanda.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 75,
          'name' => 'paises bajos',
          'flag' => 'paises-bajos.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 76,
          'name' => 'pakistan',
          'flag' => 'pakistan.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 77,
          'name' => 'palestina',
          'flag' => 'palestina.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 78,
          'name' => 'panama',
          'flag' => 'panama.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 79,
          'name' => 'paraguay',
          'flag' => 'paraguay.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 80,
          'name' => 'peru',
          'flag' => 'peru.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 81,
          'name' => 'polonia',
          'flag' => 'polonia.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 82,
          'name' => 'portugal',
          'flag' => 'portugal.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 83,
          'name' => 'puerto rico',
          'flag' => 'puerto-rico.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 84,
          'name' => 'reino unido',
          'flag' => 'reino-unido.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 85,
          'name' => 'sudafrica',
          'flag' => 'sudafrica.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 86,
          'name' => 'republica dominicana',
          'flag' => 'republica-dominicana.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 87,
          'name' => 'eslovaquia',
          'flag' => 'eslovaquia.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 88,
          'name' => 'rumania',
          'flag' => 'rumania.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 89,
          'name' => 'rusia',
          'flag' => 'rusia.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 90,
          'name' => 'senegal',
          'flag' => 'senegal.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 91,
          'name' => 'serbia',
          'flag' => 'serbia.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 92,
          'name' => 'singapur',
          'flag' => 'singapur.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 93,
          'name' => 'siria',
          'flag' => 'siria.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 94,
          'name' => 'sudan',
          'flag' => 'sudan.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 95,
          'name' => 'suecia',
          'flag' => 'suecia.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 96,
          'name' => 'suiza',
          'flag' => 'suiza.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 97,
          'name' => 'tailandia',
          'flag' => 'tailandia.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 98,
          'name' => 'taiwan',
          'flag' => 'taiwan.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 99,
          'name' => 'togo',
          'flag' => 'togo.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 100,
          'name' => 'trinidad tobago',
          'flag' => 'trinidad-tobago.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 101,
          'name' => 'tunez',
          'flag' => 'tunez.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 102,
          'name' => 'turquia',
          'flag' => 'turquia.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 103,
          'name' => 'ucrania',
          'flag' => 'ucrania.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 104,
          'name' => 'uruguay',
          'flag' => 'uruguay.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 105,
          'name' => 'venezuela',
          'flag' => 'venezuela.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 106,
          'name' => 'vietnam',
          'flag' => 'vietnam.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
        [
          'id' => 107,
          'name' => 'zimbabue',
          'flag' => 'zimbabue.svg',
          'created_at' => Carbon::now(),
          'updated_at' => Carbon::now(),
        ],
      ]);
    }
  }
